### ISSUE TITLE
[BUG] cdk8 init python-app issue

### ISSUE THREAD

**Issue by abhioncbr** [awslabs/cdk8s#166] opened 2020-05-15 20:46 UTC
**Describe the bug**
Failed cdk8 init python-app.

**To Reproduce**
```bash
cdk8s init python-app
Initializing a project from the python-app template
Creating a virtualenv for this project…
Pipfile: /Users/abhioncbr/work/github/vs-studio/kubernetes-example/k8s-automation-examples/cdk8s/cdk8s-python-hello-app/Pipfile
Using /usr/bin/python3 (3.7.3) to create virtualenv…
⠴ Creating virtual environment...created virtual environment CPython3.7.3.final.0-64 in 959ms
  creator CPython3Posix(dest=/Users/abhioncbr/.local/share/virtualenvs/cdk8s-python-hello-app-3p6dWTxc, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/Users/abhioncbr/Library/Application Support/virtualenv/seed-app-data/v1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

✔ Successfully created virtual environment! 
Virtualenv location: /Users/abhioncbr/.local/share/virtualenvs/cdk8s-python-hello-app-3p6dWTxc
Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/2018.11.26_4/libexec/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/Cellar/pipenv/2018.11.26_4/libexec/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/2018.11.26_4/libexec/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/pipenv/2018.11.26_4/libexec/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/pipenv/2018.11.26_4/libexec/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/pipenv/2018.11.26_4/libexec/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/2018.11.26_4/libexec/lib/python3.8/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/Cellar/pipenv/2018.11.26_4/libexec/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/2018.11.26_4/libexec/lib/python3.8/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/Cellar/pipenv/2018.11.26_4/libexec/lib/python3.8/site-packages/pipenv/cli/command.py", line 235, in install
    retcode = do_install(
  File "/usr/local/Cellar/pipenv/2018.11.26_4/libexec/lib/python3.8/site-packages/pipenv/core.py", line 1734, in do_install
    ensure_project(
  File "/usr/local/Cellar/pipenv/2018.11.26_4/libexec/lib/python3.8/site-packages/pipenv/core.py", line 579, in ensure_project
    path_to_python = which("python") or which("py")
  File "/usr/local/Cellar/pipenv/2018.11.26_4/libexec/lib/python3.8/site-packages/pipenv/core.py", line 108, in which
    raise RuntimeError("location not created nor specified")
RuntimeError: location not created nor specified
cdk8s init TYPE

Create a new cdk8s project from a template.

Positionals:
  TYPE  Project type                                                                       [required] [choices: "python-app", "typescript-app"]

Options:
  --version        Show version number                                                                                                [boolean]
  --help           Show help                                                                                                          [boolean]
  --dist           Install dependencies from a "dist" directory (for development)                                                      [string]
  --cdk8s-version  The cdk8s version to use when creating the new project                                          [string] [default: "0.20.0"]

Error: Command failed: pipenv install
    at checkExecSyncError (child_process.js:611:11)
    at execSync (child_process.js:647:15)
    at Object.exports.post (/usr/local/Cellar/cdk8s/0.20.0/libexec/lib/node_modules/cdk8s-cli/templates/python-app/.hooks.sscaff.js:22:3)
    at executePostHook (/usr/local/Cellar/cdk8s/0.20.0/libexec/lib/node_modules/cdk8s-cli/node_modules/sscaff/lib/sscaff.js:61:37)
    at Object.sscaff (/usr/local/Cellar/cdk8s/0.20.0/libexec/lib/node_modules/cdk8s-cli/node_modules/sscaff/lib/sscaff.js:28:15)
    at async Object.handler (/usr/local/Cellar/cdk8s/0.20.0/libexec/lib/node_modules/cdk8s-cli/bin/cmds/init.js:29:9) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 79716,
  stdout: null,
  stderr: null
}
````

**Expected behavior**
It should create a project without nay issue.

**Additional context**

**Comment by abhioncbr** [comment] 2020-05-15 20:48
Also, it requires pipenv.

```bash
dk8s init python-app
Initializing a project from the python-app template
Unable to find "pipenv". Install from https://pipenv.kennethreitz.org
```

**Comment by deepgorthi** [comment] 2020-05-15 21:21
I was able to successfully to initialize a new project dir moments ago. I followed almost the same steps as you. But instead of doing 
```bash
$ brew install pipenv
```
as mentioned in https://pipenv.kennethreitz.org.

I did 
```bash
$ /usr/bin/pip3 install --user pipenv 
```
and that helped me successfully initialize a new project. 

Can you please try that and let me know if that helps fix the issue you are seeing? 

My thinking is that maybe the pipenv is not correctly being recognized.

It is also interesting to note that while I see it uses 

> Using /usr/bin/python3 (3.7.3) to create virtualenv…

it is using 

> `"/usr/local/Cellar/pipenv/2018.11.26_4/libexec/lib/python3.8/site-packages/pipenv/core.py"` 

at runtime. 

I am not sure why there is a disconnect.

**Comment by abhioncbr** [comment] 2020-05-15 21:36
Same result in my case after following 

```bash
/usr/bin/pip3 install --user pipenv 
```

**Comment by abhioncbr** [comment] 2020-05-15 21:51
It's really funny, it did work with python3.7.7

```bash
Initializing a project from the python-app template
Creating a virtualenv for this project…
Pipfile: /Users/abhioncbr/work/github/vs-studio/kubernetes-example/k8s-automation-examples/cdk8s/cdk8s-python-hello-app/Pipfile
Using /usr/local/bin/python3 (3.7.7) to create virtualenv…
⠹ Creating virtual environment...created virtual environment CPython3.7.7.final.0-64 in 713ms
  creator CPython3Posix(dest=/Users/abhioncbr/.local/share/virtualenvs/cdk8s-python-hello-app-3p6dWTxc, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/Users/abhioncbr/Library/Application Support/virtualenv/seed-app-data/v1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

✔ Successfully created virtual environment! 
Virtualenv location: /Users/abhioncbr/.local/share/virtualenvs/cdk8s-python-hello-app-3p6dWTxc
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (a65489)!
Installing dependencies from Pipfile.lock (a65489)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Installing cdk8s~=0.20.0…
Adding cdk8s to Pipfile's [packages]…
✔ Installation Succeeded 
Pipfile.lock (099641) out of date, updating to (a65489)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✔ Success! 
Updated Pipfile.lock (099641)!
Installing dependencies from Pipfile.lock (099641)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 9/9 — 00:00:01
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
========================================================================================================

 Your cdk8s Python project is ready!

   cat help      Prints this message  
   cdk8s synth   Synthesize k8s manifests to dist/
   cdk8s import  Imports k8s API objects to "imports/k8s"

  Deploy:
   kubectl apply -f dist/*.k8s.yaml

========================================================================================================

```

**Comment by abhioncbr** [comment] 2020-05-15 22:01
Overall, It worked with python `/usr/local/bin/python3 (3.7.7)` and the latest `pipenv (2018.11.26_4)`. 

I think all the Pipfile need a change. @eladb let me know if you want that change?

**Comment by eladb** [comment] 2020-05-18 05:45
@abhioncbr yes please!

**Comment by jmarcos-cano** [comment] 2020-05-19 01:15
same issue here:

after installing using brew, installing pipenv using `pip3 install --user pipenv`  and creating first app it crashes? (not sure if it really crashes it actually creates the files but exit code 1

```
$ cdk8s init python-app

Initializing a project from the python-app template
Traceback (most recent call last):
  File "/Users/marcoscano/Library/Python/3.7/lib/python/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/Users/marcoscano/Library/Python/3.7/lib/python/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/marcoscano/Library/Python/3.7/lib/python/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pipenv 2018.11.26 (/Users/marcoscano/Library/Python/3.7/lib/python/site-packages), Requirement.parse('pipenv==2018.7.1'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/2018.7.1/libexec/bin/pipenv", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Users/marcoscano/Library/Python/3.7/lib/python/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/Users/marcoscano/Library/Python/3.7/lib/python/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/Users/marcoscano/Library/Python/3.7/lib/python/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/marcoscano/Library/Python/3.7/lib/python/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/marcoscano/Library/Python/3.7/lib/python/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/marcoscano/Library/Python/3.7/lib/python/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pipenv==2018.7.1' distribution was not found and is required by the application
cdk8s init TYPE

Create a new cdk8s project from a template.

Positionals:
  TYPE  Project type                                                                                                                                                                                                                                                    [required] [choices: "python-app", "typescript-app"]

Options:
  --version        Show version number                                                                                                                                                                                                                                                                             [boolean]
  --help           Show help                                                                                                                                                                                                                                                                                       [boolean]
  --dist           Install dependencies from a "dist" directory (for development)                                                                                                                                                                                                                                   [string]
  --cdk8s-version  The cdk8s version to use when creating the new project                                                                                                                                                                                                                       [string] [default: "0.21.0"]

Error: Command failed: pipenv install
    at checkExecSyncError (child_process.js:611:11)
    at execSync (child_process.js:647:15)
    at Object.exports.post (/usr/local/Cellar/cdk8s/0.21.0/libexec/lib/node_modules/cdk8s-cli/templates/python-app/.hooks.sscaff.js:22:3)
    at executePostHook (/usr/local/Cellar/cdk8s/0.21.0/libexec/lib/node_modules/cdk8s-cli/node_modules/sscaff/lib/sscaff.js:61:37)
    at Object.sscaff (/usr/local/Cellar/cdk8s/0.21.0/libexec/lib/node_modules/cdk8s-cli/node_modules/sscaff/lib/sscaff.js:28:15)
    at async Object.handler (/usr/local/Cellar/cdk8s/0.21.0/libexec/lib/node_modules/cdk8s-cli/bin/cmds/init.js:29:9) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 11542,
  stdout: null,
  stderr: null
}

```

```bash
$ python3 --version
Python 3.7.7
```

**Comment by iliapolo** [comment] 2020-05-19 15:20
I don't think it's caused solely because of the `3.7.3` version. Using `3.7.3` under `pyenv` works well:

```console
❯ cdk8s init python-app                                                                                                                                               [17:56:16]
Initializing a project from the python-app template
Creating a virtualenv for this project…
Pipfile: /private/tmp/cdk8s-python/Pipfile
Using /Users/epolon/.pyenv/versions/3.7.3/bin/python3 (3.7.3) to create virtualenv…
⠦ Creating virtual environment...created virtual environment CPython3.7.3.final.0-64 in 409ms
  creator CPython3Posix(dest=/Users/epolon/.virtualenvs/cdk8s-python-l6FwT2Fw, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/Users/epolon/Library/Application Support/virtualenv/seed-app-data/v1.0.1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

✔ Successfully created virtual environment!
Virtualenv location: /Users/epolon/.virtualenvs/cdk8s-python-l6FwT2Fw
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (a65489)!
Installing dependencies from Pipfile.lock (a65489)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Installing cdk8s~=0.21.0…
Adding cdk8s to Pipfile's [packages]…
✔ Installation Succeeded
.....
.....
```

@abhioncbr The failure happened for you when `pipenv` was using `/usr/bin/python3`, which is the stock python distro that comes with the OS. I suspect the issue lies somewhere there. 
I suspect it might also be an issue with `pipenv`, since the logs clearly state:

```console
✔ Successfully created virtual environment! 
Virtualenv location: /Users/abhioncbr/.local/share/virtualenvs/cdk8s-python-hello-app-3p6dWTxc
```

Immediately after this, `pipenv` checks that the virtualenv was created with the correct python version, as specified in the `Pipfile`:

https://github.com/pypa/pipenv/blob/742ae1b99b335ffb6d83a2240035af739cacafff/pipenv/core.py#L576-L579

And for some reason, it fails to locate the virtualenv it just created. 

https://github.com/pypa/pipenv/blob/742ae1b99b335ffb6d83a2240035af739cacafff/pipenv/core.py#L104-L108

Freaky!

@jmarcos-cano, regarding the error you saw:

> pkg_resources.VersionConflict: (pipenv 2018.11.26 (/Users/marcoscano/Library/Python/3.7/lib/python/site-packages), Requirement.parse('pipenv==2018.7.1'))

Well, that one is even stranger. Any chance you had an earlier version of `pipenv` installed globally? Not sure how that would explain everything, but its a lead...Were you able to workaround the problem? I imagine a cleanup of the installed packages would do the trick. 

In any case, I don't think these failures point to a systematic problem with `cdk8s init`. 

I'm still trying to get to the bottom of this though.

**Comment by abhioncbr** [comment] 2020-05-19 15:38
@iliapolo well, I used python packages in my local dev environment first time for this project. I am not sure about the issue, but with python 3.7.7, it worked. Definitely need more digging.

**Comment by wonderflow** [comment] 2020-05-25 11:46
+1 with the same issue, and for anyone who is facing this issue, you can install python 3.7.7 and switch pipenv to your new installed path of python.

For me:

```
# this install python 3.7.7 to path /usr/local/Cellar/python/3.7.7/bin/python3
brew upgrade python
# swith this version
pipenv --python /usr/local/Cellar/python/3.7.7/bin/python3
```

And finally it works now:

```
➜  hello-cdk8s cdk8s init python-app
Initializing a project from the python-app template
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (a65489)!
Installing dependencies from Pipfile.lock (a65489)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Installing cdk8s~=0.22.0…
Adding cdk8s to Pipfile's [packages]…
✔ Installation Succeeded
Pipfile.lock (31f339) out of date, updating to (a65489)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✔ Success!
```

**Comment by iliapolo** [comment] 2020-05-30 14:55
After another round of debugging, i'm still unable to reproduce the issue. 
I've tried various permutations of `python/pipenv` using all suggested installation methods.

The errors reported here happen when using the **stock** python 3.7.3 distribution that is bundled with MacOS. Being the stock version, i'm not exactly sure how to create this setup, as any python installation will result in what I presume is a slightly different state. 

One thing to note is that I also tried installing python 3.7.3 using brew:

```console
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/c24d6bcd4795e9263617e49f340cc61498eea5d3/Formula/python.rb
```

And this resulted in other errors:

```console
Error:  An error occurred while installing cdk8s~=0.21.0!
Error text: Could not fetch URL https://pypi.org/simple/cdk8s/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/cdk8s/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cdk8s/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cdk8s/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cdk8s/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cdk8s/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cdk8s/
ERROR: Could not find a version that satisfies the requirement cdk8s~=0.21.0 (from -r /var/folders/mb/5zx1h88x2891nhk4qpr6_zc8jcqzm6/T/pipenv-tki416tf-requirements/pipenv-le5ygte6-requirement.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for cdk8s~=0.21.0 (from -r /var/folders/mb/5zx1h88x2891nhk4qpr6_zc8jcqzm6/T/pipenv-tki416tf-requirements/pipenv-le5ygte6-requirement.txt (line 1))

``` 

Which further confirms that the combination of `pipenv` with a brew managed python version `3.7.3` is somehow broken. 

If anyone encounters this issue, we recommend upgrading to python `3.7.7` (`brew install python`) or using [pyenv](https://github.com/pyenv/pyenv) to install any version you like (verified `pyenv` installation of 3.7.3 works well).

Closing this issue for now, but if anyone has a reproduction please feel free to re-open an share it, I will be more than happy to debug and get to the bottom of it.

**Closed by iliapolo** 2020-05-30 14:55 UTC
Labels: bug
